project_id = "fhbeoztlwelmhpoxwjix"

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-shipping-notification]
verify_jwt = false

[functions.send-delivery-confirmation]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-order-cancelled]
verify_jwt = false